before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no 
  - conda update --quiet conda
  - conda info --all
  - conda create --name default --quiet cython h5py libtiff lxml mysql-python pandas pyzmq scikit-image scikit-learn wxpython
  - source activate default
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - pip install -e .
language: python
notifications:
  email: false
python:
  - 2.7
script:
  - python external_dependencies.py
  - python setup.py install
  - python setup.py test
