before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no 
  - conda update --quiet conda
  - conda info --all
  - conda create --name default --quiet h5py libtiff lxml matplotlib mysql-python numpy pandas pytest pyzmq scikit-image scikit-learn scipy wxpython
  - source activate default
install:
  - pip install --editable .
language: python
notifications:
  email: false
python:
  - 2.7
script:
  - python setup.py test
